### ISSUE TITLE
Widget showing ... instead of price

### ISSUE THREAD

**Issue by krishnawhite** [Alex-Werner/dash-price#1]
The current Dash price is about $22.27, but the widget shows '...' and when I hover over it, it says 'Dash Price'.

<img width="149" alt="screen shot 2017-02-20 at 13 28 13" src="https://cloud.githubusercontent.com/assets/5566533/23126823/75cc5270-f770-11e6-8acf-b9dd844ecc8a.png">

**Comment by krishnawhite** [comment]
I resolved this by setting precision to 1 dp, but there seems to be a bug when using the default settings.

**Comment by Alex-Werner** [comment]
Hi ! Thank you for your issue ! 
I had this issue, which should be resolved now. 
Can you confirm that this happens with the last version "1.2.3" ? 

You can see the version value by setting this URI in the Chrome navigator "chrome://extensions/".

If it's the 1.2.3, I therefore still have an issue (in all case I will triple check it later this day). 
Could you go into the extension page, in the Dash Price you should have 
`Inspect View background.html options.html` (If not, you might need to click on `developer mode` in the upside of the page. 

Then, clicking in "background.html" should open a new window. 
Do you there have some red lines (errors) ? If so, could you screen it ? 
If not, could you click on "options" then do  "CTRL+MAJ+I" > "Console" and screen the errors you might have (in red). 
If none, last things, could you go into "CTRL+MAJ+I" > "Application" > "Local Storage" > "chrome-extension://acgkalgdbjdhcfofjhmogbkfgelmfloo/" and screen the table you see there (with currency, currencyExchangesRates etc...) ? 

Here are the different screen in order to guide you.

**Comment by Alex-Werner** [comment]
![image](https://cloud.githubusercontent.com/assets/5849920/23127640/14f4a0ae-f77c-11e6-90d3-639ccb759d01.png)

![image](https://cloud.githubusercontent.com/assets/5849920/23127657/1eab217c-f77c-11e6-99fb-dedb7c44c5e8.png)

![image](https://cloud.githubusercontent.com/assets/5849920/23127678/30c79f52-f77c-11e6-9169-835dc7449d43.png)

![image](https://cloud.githubusercontent.com/assets/5849920/23127702/45997ae0-f77c-11e6-99b3-eff9cc898f39.png)

**Comment by Alex-Werner** [comment]
In all case, **thank you for reporting it.** 

I will do a little checker, that will validate the saved data in order to be sure that if a issue happens, it won't allow to corrupt the data (which create that bug). 
You might see that update coming in approx. 8hrs.

**Comment by Alex-Werner** [comment]
@krishnawhite I've updated to 1.3.0, it should be fixed now (added a validation of the saved data before loading)
